#!/usr/bin/env bash
# This script installs and configures Nginx web server

apt-get update
apt-get -y install nginx

# Configure Nginx to listen on port 80
sed -i 's/^\(listen\s*\)80;/\180;/g' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart > /dev/null

# Create a custom index.html page with the string "Hello World!"
echo "Hello World!" > /var/www/html/index.html
