#!/usr/bin/env bash

# Update and upgrade packages
sudo apt update -y
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Create a custom 404.html page with the desired content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sudo sed -i 's/^\(server\s*{\)$/\1\n    error_page 404 /404.html;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
