#!/usr/bin/env bash
# Check if an IP address is provided as an argument
if [ -z "$1" ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the IP 5 times
for ((i=1; i<=5; i++)); do
    ping -c 1 $1
done
