#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# Create the PID file
echo $$ > /var/run/myscript.pid

# Set up signal handling
trap "echo I hate the kill command" TERM
trap "echo Y U no love me?!" INT
trap "rm /var/run/myscript.pid; exit" QUIT TERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
