#!/usr/bin/env bash
# This script displays "Best School" 10 times, but says "Hi" on the 9th iteration

count=0
while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]; then
        echo "Hi"
    fi
    echo "Best School"
    count=$((count+1))
done
